### ISSUE TITLE
Uncaught TypeError when adding newly uploaded image to editor

### ISSUE THREAD

**Issue by montchr** [wp-shortcake/image-shortcake#59]
Full error message (with unnecessary path removed):

```
Uncaught TypeError: Cannot read property 'get' of undefined ... path/to/shortcake/js/build/shortcode-ui.js?ver=0.7.0-alpha line 1608
```

This only happens with the image shortcode, not other shortcodes I've added. It also only happens for newly-uploaded images. If I add the image to editor from the library again after reloading the page, the error does not occur.

Edit: I should add that the image appears in the editor despite the error.

**Comment by goldenapples** [comment]
I think the bug is actually in Shortcake, and submitted it there: https://github.com/wp-shortcake/shortcake/issues/538

Closing this report unless we can isolate it more closely to something happening in Image Shortcake.

**Comment by montchr** [comment]
:+1: thanks
